version: '3.7'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "Postgres@2020"
    ports:
      - "5432:5432"
    volumes:
      - C:\pg:/var/lib/postgresql/data
    networks:
      - postgres-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "rodrigodp2014@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "Postgres@2020"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge
